version: "3.8"

services:
  flask-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    restart: always
